networks:
  app-network:
    driver: bridge

volumes:
  test-reports:
    driver: local
  sonar-data:
    driver: local 

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: jest-tests-dev
    environment:
      TARGET: ${TARGET_DEV}
      NODE_ENV: ${NODE_ENV_DEV}
      BASE_URL: ${BASE_URL}
      AUTH_EMAIL: ${AUTH_EMAIL}
      AUTH_PASSWORD: ${AUTH_PASSWORD}
      DEBUG_REQUESTS: ${DEBUG_REQUESTS}
    volumes:
      - test-reports:/app/out/report
      - ./out/report:/app/out/report
    command: npm run test:dev
    networks:
      - app-network
    restart: "no"

  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: jest-tests-prod
    profiles:
      - prod
    environment:
      TARGET: ${TARGET_PROD}
      NODE_ENV: ${NODE_ENV_PROD}
      BASE_URL: ${BASE_URL}
      AUTH_EMAIL: ${AUTH_EMAIL}
      AUTH_PASSWORD: ${AUTH_PASSWORD}
      DEBUG_REQUESTS: ${DEBUG_REQUESTS}
    volumes:
      - ./out/report:/app/out/report
    command: npm run test:prod
    networks:
      - app-network
    restart: "no"

  report:
    image: nginx:alpine
    container_name: jest-report-server
    profiles:
      - report
    ports:
      - "${REPORT_PORT}:80"
    volumes:
      - ./out/report:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - app-network
    restart: unless-stopped


  # profile ci 
  ci:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: jest-ci-local
    profiles:
      - ci
    environment:
      TARGET: ${TARGET_DEV}
      NODE_ENV: ${NODE_ENV_TEST}
      BASE_URL: ${BASE_URL}
      AUTH_EMAIL: ${AUTH_EMAIL}
      AUTH_PASSWORD: ${AUTH_PASSWORD}
      DEBUG_REQUESTS: ${DEBUG_REQUESTS}
    volumes:
      - ./out:/app/out
    command: >
      sh -c "
        echo '🚀 Iniciando pipeline CI local...' &&
        echo '🧪 Rodando testes...' &&
        npm run test:dev &&
        echo '🔍 Rodando SonarQube...' &&
        sleep 5 &&
        echo '✅ Pipeline finalizado com sucesso!' ||
        (echo '❌ Pipeline falhou!' && exit 1)
      "
    networks:
      - app-network
    restart: "no"

  sonar-db:
    image: postgres:15-alpine
    volumes:
      - sonar-data:/var/lib/postgresql/data
    container_name: sonar-db
    profiles:
      - ci
    environment:
      POSTGRES_USER: ${SONAR_DB_USER}
      POSTGRES_PASSWORD: ${SONAR_DB_PASSWORD}
      POSTGRES_DB: ${SONAR_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sonar -d sonarqube"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - app-network
    restart: "no"

  sonarqube:
    image: sonarqube:10.6-community
    container_name: sonarqube
    profiles:
      - ci
    depends_on:
      sonar-db:
        condition: service_healthy
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar-db:5432/${SONAR_DB_NAME}
      SONAR_JDBC_USERNAME: ${SONAR_DB_USER}
      SONAR_JDBC_PASSWORD: ${SONAR_DB_PASSWORD}
    ports:
      - "${SONAR_PORT}:9000"
    networks:
      - app-network
    restart: "no"

  sonar-scanner:
    image: sonarsource/sonar-scanner-cli:5
    container_name: sonar-scanner
    profiles:
      - ci
    depends_on:
      - sonarqube
    working_dir: /usr/src
    volumes:
      - ./:/usr/src
    environment:
      SONAR_HOST_URL: ${SONAR_HOST_URL}
      SONAR_TOKEN: ${SONAR_TOKEN}
    networks:
      - app-network
    entrypoint: >
      sh -c "
        echo '⏳ Aguardando SonarQube ficar pronto...' &&
        until curl -s http://sonarqube:9000/api/system/status | grep -q 'UP'; do
          echo '⏳ Subindo Sonar...';
          sleep 5;
        done &&
        echo '🚀 Sonar pronto! Rodando scanner...' &&
        sonar-scanner
      "