services:
  - type: web
    name: jest-supertest-starter
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TARGET
        value: prod
      - key: BASE_URL
        value: https://reqres.in
      - key: AUTH_EMAIL
        value: eve.holt@reqres.in
      - key: AUTH_PASSWORD
        value: cityslicka